# DAT210x - Programming with Python for DS

## Module2 - Lab3

In [2]:
# Import and alias Pandas
import pandas as pd

Often, you will want to load a dataset that is missing explicit header labels. You won't know if your data lacks headers or not unless you load it up and examine the headers to see if they make sense. Pandas by default reads in the first row of data as the header. If that isn't the case for your specific data set, you will lose your first data row. Be careful!

Load up the `Servo.data` dataset. Examine the headers, and adjust them as necessary, if need be.

In [9]:
url = 'Datasets\\servo.data'
df = pd.read_csv(url, names = ['motor', 'screw', 'pgain', 'vgain', 'class'])

Let's try experimenting with some slicing. Create a slice that contains all entries that have a vgain equal to 5. Then print the length of (# of samples in) that slice:

In [11]:
df[df.vgain == 5]

    motor screw  pgain  vgain     class
1       B     D      6      5  0.506252
4       D     B      6      5  0.356251
8       C     A      6      5  0.768754
10      B     E      6      5  0.468752
22      B     C      6      5  0.468752
24      A     B      6      5  0.581253
25      E     C      6      5  0.393752
34      C     C      6      5  0.506252
38      C     B      6      5  0.543753
50      D     A      6      5  0.431252
70      B     A      6      5  0.806255
73      A     E      6      5  0.506252
81      A     C      6      5  0.506252
84      E     A      6      5  0.581253
95      A     D      6      5  0.506252
108     E     B      6      5  0.431252
112     C     D      6      5  0.468752
117     E     D      6      5  0.318751
132     E     E      6      5  0.281251
135     B     B      6      5  0.543753
161     C     E      6      5  0.468752
166     A     A      6      5  0.806255

Create a slice that contains all entries having a motor equal to E and screw equal to E. Then print the length of (# of samples in) that slice:

In [16]:
df[(df.motor == 'E') & (df.screw == 'E')]

    motor screw  pgain  vgain     class
0       E     E      5      4  0.281251
35      E     E      3      2  1.100000
86      E     E      4      3  0.843755
132     E     E      6      5  0.281251
140     E     E      4      2  0.506252
151     E     E      3      1  0.700001

Create a slice that contains all entries having a pgain equal to 4. Use one of the various methods of finding the mean vgain value for the samples in that slice. Once you've found it, print it:

In [17]:
df[df.pgain == 4].describe()

       pgain      vgain      class
count   66.0  66.000000  66.000000
mean     4.0   2.060606   0.673298
std      0.0   0.820484   0.314105
min      4.0   1.000000   0.131250
25%      4.0   1.000000   0.365627
50%      4.0   2.000000   0.712504
75%      4.0   3.000000   0.956256
max      4.0   3.000000   1.218740

Here's a bonus activity for you. See what happens when you display the `.dtypes` property of your dataframe!

In [19]:
df.dtypes

motor     object
screw     object
pgain      int64
vgain      int64
class    float64
dtype: object